#include QMK_KEYBOARD_H


enum combos { 
	COMM_DOT_SCLN,
};

const uint16_t PROGMEM comm_dot_scln[] = { KC_COMM, KC_DOT, COMBO_END};

combo_t key_combos[COMBO_COUNT] = {
  [COMM_DOT_SCLN] = COMBO(comm_dot_scln, KC_SCLN),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3(KC_NO, KC_Q, KC_X, KC_M, KC_W, KC_V, KC_K, KC_F, KC_O, KC_U, KC_QUOT, KC_NO, KC_NO, LGUI_T(KC_N), LSFT_T(KC_R), LALT_T(KC_T), LCTL_T(KC_S), KC_G, KC_Y, RCTL_T(KC_H), RALT_T(KC_A), RSFT_T(KC_E), RGUI_T(KC_I), KC_NO, KC_NO, KC_B, KC_L, KC_D, KC_C, KC_J, KC_Z, KC_P, KC_COMM, KC_DOT, KC_SLSH, KC_NO, MO(5), LT(2,KC_BSPC), LCAG_T(KC_DEL), KC_ENT, LT(3,KC_SPC), MO(5)),
    [1] = LAYOUT_split_3x6_3(KC_TAB, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LGUI, KC_TRNS, KC_SPC, KC_ENT, MO(3), KC_RALT),
    [2] = LAYOUT_split_3x6_3(KC_NO, KC_ESC, MS_BTN2, MS_BTN3, MS_BTN1, KC_NO, KC_NO, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_NO, KC_NO, KC_LGUI, KC_LSFT, KC_LALT, KC_LCTL, KC_NO, CW_TOGG, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_NO, KC_NO, LGUI(KC_Z), LGUI(KC_X), LGUI(KC_C), LGUI(KC_V), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, LCAG_T(KC_DEL), KC_NO, LT(4,KC_ENT), KC_NO),
    [3] = LAYOUT_split_3x6_3(KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_NO, KC_7, KC_8, KC_9, KC_EQL, KC_NO, KC_NO, LGUI_T(KC_TAB), LSFT_T(KC_BSLS), SC_LAPO, LCTL_T(KC_LBRC), KC_LCBR, KC_NO, RCTL_T(KC_4), RALT_T(KC_5), RSFT_T(KC_6), RGUI_T(KC_MINS), KC_NO, KC_NO, KC_GRV, KC_SCLN, KC_RPRN, KC_RBRC, KC_RCBR, KC_0, KC_1, KC_2, KC_3, KC_SCLN, KC_NO, KC_NO, LT(4,KC_BSPC), LCAG_T(KC_DEL), KC_NO, KC_TRNS, KC_NO),
    [4] = LAYOUT_split_3x6_3(KC_NO, KC_ESC, KC_BRID, KC_BRIU, KC_NO, KC_NO, KC_NO, KC_F7, KC_F8, KC_F9, KC_F11, KC_NO, KC_NO, KC_LGUI, KC_LSFT, KC_LALT, KC_LCTL, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_F12, KC_NO, KC_NO, KC_MUTE, KC_VOLD, KC_VOLU, KC_NO, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_F10, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_TRNS, KC_NO),
    [5] = LAYOUT_split_3x6_3(KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS),
};
